parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Floorfy\Domain\Model\Property\PropertyRepository:
    class: Floorfy\Infrastructure\Persistence\Doctrine\Repository\DoctrinePropertyRepository
    factory: ["@doctrine", getRepository]
    arguments: ["DomainModel:Property\\Property"]

  Floorfy\Domain\Model\Property\PropertyBuilder:
    class: Floorfy\Domain\Model\Property\PropertyBuilder

  Floorfy\Domain\Model\Property\TourBuilder:
    class: Floorfy\Domain\Model\Property\TourBuilder