doctrine_migrations:
    #dir_name: '%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/Migrations'
    #namespace: Floorfy\Infrastructure\Persistence\Doctrine\Migrations
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/Migrations'
    enable_profiler: '%kernel.debug%'
