framework:
    messenger:
        buses:
            event.bus:
                default_middleware: allow_no_handlers
            command.bus: ~
            query.bus: ~
        default_bus: event.bus
        transports:
            sync: 'sync://'

        routing:
            Floorfy\Application\Command\Property\CreatePropertyCommand: sync
